# Generated by Django 4.1.4 on 2022-12-28 05:44

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='imagevideo',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to=api.models.video_upload, validators=[django.core.validators.FileExtensionValidator(['MP4', 'WEBM', 'MPG', 'MP2', 'MPEG', 'MPE', 'MPV', 'OGG', 'M4P', 'M4V', 'AVI', 'WMV'])]),
        ),
    ]
