# Generated by Django 3.1.5 on 2022-12-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(default='09:42:53'),
        ),
    ]
